ALTER SESSION SET CONTAINER=DBDOCK_TEST_01;

CREATE USER "CONSEP" IDENTIFIED BY "default"  ;

GRANT CREATE SESSION TO CONSEP;
GRANT CONNECT, RESOURCE TO CONSEP;

grant select any table to CONSEP ;
grant select on sys.dba_objects to CONSEP;
grant READ on sys.dba_objects to CONSEP;
grant select_catalog_role to CONSEP;
grant execute on dbms_metadata to CONSEP;

GRANT SELECT ANY DICTIONARY TO CONSEP;

GRANT CREATE TABLE TO CONSEP;
GRANT CREATE VIEW TO CONSEP;
GRANT CREATE PROCEDURE TO CONSEP;
GRANT CREATE SEQUENCE TO CONSEP;
GRANT CREATE TRIGGER TO CONSEP;
GRANT DROP ANY TABLE TO CONSEP;


ALTER USER CONSEP QUOTA UNLIMITED ON USERS;
