
  CREATE OR REPLACE EDITIONABLE TYPE "THE"."SIL_ERROR_PARAMS" AS
VARRAY(50) OF VARCHAR2(500)
/
;

  CREATE OR REPLACE EDITIONABLE TYPE "THE"."SIL_ERROR_MESSAGE" AS OBJECT
(
  DATABASE_FIELD                 VARCHAR2(50),
  MESSAGE                        VARCHAR2(250),
  PARAMS                         SIL_ERROR_PARAMS,
  WARNING_FLAG                   VARCHAR2(1)
)
/
;

  CREATE OR REPLACE EDITIONABLE TYPE "THE"."SIL_ERROR_MESSAGES" AS
VARRAY(100) OF SIL_ERROR_MESSAGE
/
;

  CREATE OR REPLACE EDITIONABLE TYPE "THE"."CBR_VARCHAR2_ARRAY" as table of varchar2(255)
/
;
