
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "THE"."EXPORT_PERMIT_VIEW" ("ORG_UNIT_NO", "EXPORT_TRANSPORT_TYPE_CODE", "EXPORT_PORT_OF_EXPORT_CODE", "TRANSPORT_NAME", "ESTIMATED_SHIPPING_DATE", "EXPORT_PERMIT_DETAIL_NUMBER", "EXPORT_PERMIT_STATUS_CODE", "CLIENT_NUMBER", "PERMIT_VOLUME", "EXPORT_COUNTRY_CODE", "EXEMPTION_NUMBER", "RECEIVED_DATE", "EXPORT_PERMIT_ISSUE_DATE", "JURISDICTION") AS 
  SELECT A.ORG_UNIT_NO,
       A.EXPORT_TRANSPORT_TYPE_CODE,
       A.EXPORT_PORT_OF_EXPORT_CODE,
       A.TRANSPORT_NAME,
       A.ESTIMATED_SHIPPING_DATE,
       A.EXPORT_PERMIT_DETAIL_NUMBER,
       A.EXPORT_PERMIT_STATUS_CODE,
       A.CLIENT_NUMBER,
       A.PERMIT_VOLUME,
       A.EXPORT_COUNTRY_CODE,
       A.EXEMPTION_NUMBER,
       A.RECEIVED_DATE,
       A.EXPORT_PERMIT_ISSUE_DATE,
	   'P' AS JURISDICTION
  FROM EXPORT_PERMIT_DETAIL A
UNION
-- RESERVE PERMITS
SELECT DISTINCT B.ORG_UNIT_NO,
       B.EXPORT_TRANSPORT_TYPE_CODE,
       B.EXPORT_PORT_OF_EXPORT_CODE,
       B.TRANSPORT_NAME,
       B.ESTIMATED_SHIPPING_DATE,
       B.EXPORT_INDIAN_RSRV_PRMT_DTL_ID AS EXPORT_PERMIT_DETAIL_NUMBER,
       'ACT' AS EXPORT_PERMIT_STATUS_CODE,
       B.CLIENT_NUMBER,
       NVL((SELECT SUM(EP.PACKAGE_VOLUME) FROM EXPORT_PACKAGE EP WHERE EP.EXPORT_INDIAN_RSRV_PRMT_DTL_ID = B.EXPORT_INDIAN_RSRV_PRMT_DTL_ID), 0) AS PERMIT_VOLUME,
       B.EXPORT_COUNTRY_CODE,
       NULL AS EXEMPTION_NUMBER,
       B.ENTRY_TIMESTAMP AS RECEIVED_DATE,
       B.ENTRY_TIMESTAMP AS EXPORT_PERMIT_ISSUE_DATE,
	   'I' AS JURISDICTION
  FROM EXPORT_INDIAN_RSRV_PRMT_DTL B
UNION
-- FEDERAL PERMITS
SELECT DISTINCT C.ORG_UNIT_NO,
       C.EXPORT_TRANSPORT_TYPE_CODE,
       C.EXPORT_PORT_OF_EXPORT_CODE,
       C.TRANSPORT_NAME,
       C.ESTIMATED_SHIPPING_DATE,
       C.EXPORT_FED_PERMIT_DETAIL_ID AS EXPORT_PERMIT_DETAIL_NUMBER,
       'ACT' AS EXPORT_PERMIT_STATUS_CODE,
       C.CLIENT_NUMBER,
       NVL((SELECT SUM(EP.PACKAGE_VOLUME) FROM EXPORT_PACKAGE EP WHERE EP.EXPORT_FED_PERMIT_DETAIL_ID = C.EXPORT_FED_PERMIT_DETAIL_ID), 0) AS PERMIT_VOLUME,
       C.EXPORT_COUNTRY_CODE,
       NULL AS EXEMPTION_NUMBER,
       C.ENTRY_TIMESTAMP AS RECEIVED_DATE,
       C.ENTRY_TIMESTAMP AS EXPORT_PERMIT_ISSUE_DATE,
	   'F' AS JURISDICTION
  FROM EXPORT_FEDERAL_PERMIT_DETAIL C;

  CREATE TABLE "THE"."EXPORT_PERMIT" 
   (	"PERMIT_TYPE_CODE" VARCHAR2(1) NOT NULL ENABLE, 
	"EXPORT_PERMIT_NMBR" NUMBER(10,0) NOT NULL ENABLE, 
	"EXP_PRMT_SEQ_NMBR" NUMBER(5,0) NOT NULL ENABLE, 
	"EXP_PRMT_STS_CODE" VARCHAR2(1) NOT NULL ENABLE, 
	"EXEMPTION_NUMBER" VARCHAR2(8) NOT NULL ENABLE, 
	"EXEMPTION_TYPE_CDE" VARCHAR2(1) NOT NULL ENABLE, 
	"DEST_COMP_NAME" VARCHAR2(52) NOT NULL ENABLE, 
	"DEST_CITY" VARCHAR2(30) NOT NULL ENABLE, 
	"DEST_COUNTRY" VARCHAR2(16) NOT NULL ENABLE, 
	"TRANSPORT_TYPE_CDE" VARCHAR2(1) NOT NULL ENABLE, 
	"TRANSPORTNAME" VARCHAR2(26) NOT NULL ENABLE, 
	"EST_SHIPPING_DATE" DATE NOT NULL ENABLE, 
	"PORT_OF_EXPORT" VARCHAR2(34) NOT NULL ENABLE, 
	"APPLICATION_DATE" DATE NOT NULL ENABLE, 
	"RECEIVED_DATE" DATE NOT NULL ENABLE, 
	"EXP_PRMT_ISSUE_DTE" DATE NOT NULL ENABLE, 
	"RECEIPT_NUMBER" VARCHAR2(8) NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"PERMITTED_VOLUME" NUMBER(9,2) NOT NULL ENABLE, 
	"ADJUSTED_VOLUME" NUMBER(9,2) NOT NULL ENABLE, 
	"NUMBER_OF_PIECES" NUMBER(10,0) NOT NULL ENABLE, 
	"NUMBER_OF_LOADS" NUMBER(5,0) NOT NULL ENABLE, 
	"FEE_IN_LIEU_M3" NUMBER(5,2) NOT NULL ENABLE, 
	"ORG_UNIT_NO" NUMBER(10,0) NOT NULL ENABLE, 
	"SCALED_FLAG" VARCHAR2(1) NOT NULL ENABLE, 
	"METHOD_OF_SCALE_CD" VARCHAR2(1) NOT NULL ENABLE, 
	"CLIENT_NUMBER" VARCHAR2(8) NOT NULL ENABLE, 
	"CLIENT_LOCN_CODE" VARCHAR2(2) NOT NULL ENABLE, 
	"EXT1042_NUMBER" VARCHAR2(6) NOT NULL ENABLE, 
	"DIAND_FILE_NMBR" VARCHAR2(3) NOT NULL ENABLE, 
	"DIAND_DATE" DATE NOT NULL ENABLE, 
	"DIAND_APPROVE_IND" VARCHAR2(1) NOT NULL ENABLE, 
	"DIAND_VOLUME" NUMBER(9,1) NOT NULL ENABLE, 
	"REMARKS" VARCHAR2(254) NOT NULL ENABLE, 
	"ENTRY_USERID" VARCHAR2(30) NOT NULL ENABLE, 
	"ENTRY_TIMESTAMP" DATE NOT NULL ENABLE, 
	"UPDATE_USERID" VARCHAR2(30) NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	"REVISION_COUNT" NUMBER(5,0) NOT NULL ENABLE
   ) ;

  CREATE TABLE "THE"."FILE_CLIENT_TYPE_CODE" 
   (	"FILE_CLIENT_TYPE_CODE" VARCHAR2(1) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"EXPIRY_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "THE"."FCTC_PK" ON "THE"."FILE_CLIENT_TYPE_CODE" ("FILE_CLIENT_TYPE_CODE") 
  ;
ALTER TABLE "THE"."FILE_CLIENT_TYPE_CODE" ADD CONSTRAINT "FCTC_PK" PRIMARY KEY ("FILE_CLIENT_TYPE_CODE")
  USING INDEX "THE"."FCTC_PK"  ENABLE;

  CREATE TABLE "THE"."FOR_CLIENT_LINK" 
   (	"FOR_CLIENT_LINK_SKEY" NUMBER(10,0) NOT NULL ENABLE, 
	"FOREST_FILE_ID" VARCHAR2(10) NOT NULL ENABLE, 
	"CUTTING_PERMIT_ID" VARCHAR2(3), 
	"CUT_BLOCK_ID" VARCHAR2(10), 
	"FILE_CLIENT_TYPE" VARCHAR2(1) NOT NULL ENABLE, 
	"CLIENT_NUMBER" VARCHAR2(8) NOT NULL ENABLE, 
	"CLIENT_LOCN_CODE" VARCHAR2(2) NOT NULL ENABLE, 
	"LICENSEE_START_DT" DATE, 
	"LICENSEE_END_DATE" DATE, 
	"ENTRY_USERID" VARCHAR2(30) NOT NULL ENABLE, 
	"ENTRY_TIMESTAMP" DATE NOT NULL ENABLE, 
	"UPDATE_USERID" VARCHAR2(30) NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
	"REVISION_COUNT" NUMBER(5,0) NOT NULL ENABLE, 
	 CONSTRAINT "FCL_PFU_FK" FOREIGN KEY ("FOREST_FILE_ID")
	  REFERENCES "THE"."PROV_FOREST_USE" ("FOREST_FILE_ID") ENABLE, 
	 CONSTRAINT "FCL_CL_FK" FOREIGN KEY ("CLIENT_NUMBER", "CLIENT_LOCN_CODE")
	  REFERENCES "THE"."CLIENT_LOCATION" ("CLIENT_NUMBER", "CLIENT_LOCN_CODE") ENABLE, 
	 CONSTRAINT "FCL_FCTC_FK" FOREIGN KEY ("FILE_CLIENT_TYPE")
	  REFERENCES "THE"."FILE_CLIENT_TYPE_CODE" ("FILE_CLIENT_TYPE_CODE") ENABLE
   ) ;
  CREATE UNIQUE INDEX "THE"."I1$_FOR_CLIENT_LINK" ON "THE"."FOR_CLIENT_LINK" ("CLIENT_NUMBER", "CLIENT_LOCN_CODE", "FILE_CLIENT_TYPE", "FOREST_FILE_ID", "CUTTING_PERMIT_ID", "CUT_BLOCK_ID", "LICENSEE_START_DT") 
  ;
  CREATE UNIQUE INDEX "THE"."FCL_PK" ON "THE"."FOR_CLIENT_LINK" ("FOR_CLIENT_LINK_SKEY") 
  ;
ALTER TABLE "THE"."FOR_CLIENT_LINK" ADD CONSTRAINT "FCL_UK" UNIQUE ("FOREST_FILE_ID", "CUTTING_PERMIT_ID", "CUT_BLOCK_ID", "FILE_CLIENT_TYPE", "CLIENT_NUMBER", "CLIENT_LOCN_CODE", "LICENSEE_START_DT")
  USING INDEX "THE"."I1$_FOR_CLIENT_LINK"  ENABLE;
ALTER TABLE "THE"."FOR_CLIENT_LINK" ADD CONSTRAINT "FCL_PK" PRIMARY KEY ("FOR_CLIENT_LINK_SKEY")
  USING INDEX "THE"."FCL_PK"  ENABLE;
