
  CREATE OR REPLACE EDITIONABLE TRIGGER "THE"."TB1$_MAX_CLIENT_NMBR" BEFORE INSERT OR UPDATE ON THE.MAX_CLIENT_NMBR
FOR EACH ROW
BEGIN
:NEW.DUMMY_ACCESS_KEY :=            NVL ( RTRIM ( :NEW.DUMMY_ACCESS_KEY ), ' ' ) ;
:NEW.CLIENT_NUMBER :=            NVL ( RTRIM ( :NEW.CLIENT_NUMBER ), ' ' ) ;
END ;




/
ALTER TRIGGER "THE"."TB1$_MAX_CLIENT_NMBR" ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "THE"."TB1$_EXPORT_PERMIT" 
BEFORE INSERT OR UPDATE ON EXPORT_PERMIT
FOR EACH ROW
BEGIN
:NEW.PERMIT_TYPE_CODE   := NVL ( RTRIM ( :NEW.PERMIT_TYPE_CODE ), ' ' ) ;
:NEW.EXP_PRMT_STS_CODE  := NVL ( RTRIM ( :NEW.EXP_PRMT_STS_CODE ), ' ' ) ;
:NEW.EXEMPTION_NUMBER   := NVL ( RTRIM ( :NEW.EXEMPTION_NUMBER ), ' ' ) ;
:NEW.EXEMPTION_TYPE_CDE := NVL ( RTRIM ( :NEW.EXEMPTION_TYPE_CDE ), ' ' ) ;
:NEW.DEST_COMP_NAME     := NVL ( RTRIM ( :NEW.DEST_COMP_NAME ), ' ' ) ;
:NEW.DEST_CITY          := NVL ( RTRIM ( :NEW.DEST_CITY ), ' ' ) ;
:NEW.DEST_COUNTRY       := NVL ( RTRIM ( :NEW.DEST_COUNTRY ), ' ' ) ;
:NEW.TRANSPORT_TYPE_CDE := NVL ( RTRIM ( :NEW.TRANSPORT_TYPE_CDE ), ' ' ) ;
:NEW.TRANSPORTNAME      := NVL ( RTRIM ( :NEW.TRANSPORTNAME ), ' ' ) ;
:NEW.PORT_OF_EXPORT     := NVL ( RTRIM ( :NEW.PORT_OF_EXPORT ), ' ' ) ;
:NEW.RECEIPT_NUMBER     := NVL ( RTRIM ( :NEW.RECEIPT_NUMBER ), ' ' ) ;
:NEW.SCALED_FLAG        := NVL ( RTRIM ( :NEW.SCALED_FLAG ), ' ' ) ;
:NEW.METHOD_OF_SCALE_CD := NVL ( RTRIM ( :NEW.METHOD_OF_SCALE_CD ), ' ' ) ;
:NEW.CLIENT_NUMBER      := NVL ( RTRIM ( :NEW.CLIENT_NUMBER ), ' ' ) ;
:NEW.CLIENT_LOCN_CODE   := NVL ( RTRIM ( :NEW.CLIENT_LOCN_CODE ), ' ' ) ;
:NEW.EXT1042_NUMBER     := NVL ( RTRIM ( :NEW.EXT1042_NUMBER ), ' ' ) ;
:NEW.DIAND_FILE_NMBR    := NVL ( RTRIM ( :NEW.DIAND_FILE_NMBR ), ' ' ) ;
:NEW.DIAND_APPROVE_IND  := NVL ( RTRIM ( :NEW.DIAND_APPROVE_IND ), ' ' ) ;
:NEW.REMARKS            := NVL ( RTRIM ( :NEW.REMARKS ), ' ' ) ;
:NEW.ENTRY_USERID       := NVL ( RTRIM ( :NEW.ENTRY_USERID ), ' ' ) ;
:NEW.UPDATE_USERID      := NVL ( RTRIM ( :NEW.UPDATE_USERID ), ' ' ) ;
END ;


/
ALTER TRIGGER "THE"."TB1$_EXPORT_PERMIT" ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "THE"."TB1$_FOREST_INVC_TXN" 
  BEFORE INSERT OR UPDATE ON THE.FOREST_INVC_TXN
  FOR EACH ROW
BEGIN
  :NEW.INVOICE_NUMBER     := NVL(RTRIM(:NEW.INVOICE_NUMBER), ' ');
  :NEW.BILLING_STATUS_ST  := NVL(RTRIM(:NEW.BILLING_STATUS_ST), ' ');
  :NEW.INVOICE_CLASS_CODE := NVL(RTRIM(:NEW.INVOICE_CLASS_CODE), ' ');
  :NEW.INVOICE_TYPE_CODE  := NVL(RTRIM(:NEW.INVOICE_TYPE_CODE), ' ');
  :NEW.INVC_SUB_TYPE_CODE := NVL(RTRIM(:NEW.INVC_SUB_TYPE_CODE), ' ');
  :NEW.RELATED_INVOICE    := NVL(RTRIM(:NEW.RELATED_INVOICE), ' ');
  :NEW.CLIENT_NUMBER      := NVL(RTRIM(:NEW.CLIENT_NUMBER), ' ');
  :NEW.CLIENT_LOCN_CODE   := NVL(RTRIM(:NEW.CLIENT_LOCN_CODE), ' ');
  :NEW.ENTRY_USERID       := NVL(RTRIM(:NEW.ENTRY_USERID), ' ');
  :NEW.UPDATE_USERID      := NVL(RTRIM(:NEW.UPDATE_USERID), ' ');
END;




/
ALTER TRIGGER "THE"."TB1$_FOREST_INVC_TXN" ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "THE"."TB1$_FOREST_INVOICE" 
   BEFORE INSERT OR UPDATE ON THE.FOREST_INVOICE
   FOR EACH ROW
BEGIN
   --If HBS is inserting a blank invc_sub_type_code, then replace it with HVS
   if :NEW.INVOICE_TYPE_CODE IN ('PSI','WSI') then
      :NEW.INVC_SUB_TYPE_CODE :=   NVL ( RTRIM ( :NEW.INVC_SUB_TYPE_CODE ), 'HVS' );
   end if;
   :NEW.INVOICE_NUMBER :=       NVL ( RTRIM ( :NEW.INVOICE_NUMBER ), ' ' );
   :NEW.CANCELLATION_IND :=     NVL ( RTRIM ( :NEW.CANCELLATION_IND ), ' ' );
   :NEW.PAYABLE_BY_CLIENT :=    NVL ( RTRIM ( :NEW.PAYABLE_BY_CLIENT ), ' ' );
   :NEW.PAYABLE_BY_CLI_LOC :=   NVL ( RTRIM ( :NEW.PAYABLE_BY_CLI_LOC ), ' ' );
   :NEW.INVOICE_CLASS_CODE :=   NVL ( RTRIM ( :NEW.INVOICE_CLASS_CODE ), ' ' );
   :NEW.INVOICE_TYPE_CODE :=    NVL ( RTRIM ( :NEW.INVOICE_TYPE_CODE ), ' ' );
   :NEW.INVC_SUB_TYPE_CODE :=   NVL ( RTRIM ( :NEW.INVC_SUB_TYPE_CODE ), ' ' );
   :NEW.CANCELLED_BY_INVC :=        RTRIM ( :NEW.CANCELLED_BY_INVC );
   :NEW.RELATED_INVOICE :=          RTRIM ( :NEW.RELATED_INVOICE );
   :NEW.REPLACED_BY_INVC :=         RTRIM ( :NEW.REPLACED_BY_INVC );
   :NEW.SCALE_SITE_ID_NMBR :=       RTRIM ( :NEW.SCALE_SITE_ID_NMBR );
   :NEW.SCALER_LICENCE_NUM :=       RTRIM ( :NEW.SCALER_LICENCE_NUM );
   :NEW.VOLUME_ONLY_IND :=      NVL ( RTRIM ( :NEW.VOLUME_ONLY_IND ), ' ' );
   :NEW.COPY_TO_CLIENT :=           RTRIM ( :NEW.COPY_TO_CLIENT );
   :NEW.COPY_TO_CLI_LOC :=          RTRIM ( :NEW.COPY_TO_CLI_LOC );
   :NEW.ENTRY_USERID :=         NVL ( RTRIM ( SUBSTR(:NEW.ENTRY_USERID,0,8) ), ' ' );
   :NEW.UPDATE_USERID :=        NVL ( RTRIM ( SUBSTR(:NEW.UPDATE_USERID,0,8) ), ' ' );
   :NEW.SCALED_AT :=            NVL ( RTRIM ( :NEW.SCALED_AT ), ' ' );
END;




/
ALTER TRIGGER "THE"."TB1$_FOREST_INVOICE" ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "THE"."TB1$_GNRL_INVC_TXN" 
  BEFORE INSERT OR UPDATE ON THE.GNRL_INVC_TXN
  FOR EACH ROW
BEGIN
  :NEW.MINISTRY_REF_NUM := NVL(RTRIM(:NEW.MINISTRY_REF_NUM), ' ');
END;




/
ALTER TRIGGER "THE"."TB1$_GNRL_INVC_TXN" ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "THE"."TB1$_GENERAL_INVOICE" 
    BEFORE INSERT OR UPDATE ON THE.GENERAL_INVOICE
    FOR EACH ROW
BEGIN
  :NEW.INVOICE_NUMBER :=       NVL ( RTRIM ( :NEW.INVOICE_NUMBER ), ' ' ) ;
  :NEW.CANCELLATION_IND :=     NVL ( RTRIM ( :NEW.CANCELLATION_IND ), ' ' ) ;
--  :NEW.FOREST_FILE_ID :=       NVL ( RTRIM ( :NEW.FOREST_FILE_ID ), ' ' ) ;
  :NEW.MINISTRY_REF_NUM :=     NVL ( RTRIM ( :NEW.MINISTRY_REF_NUM ), ' ' ) ;
  :NEW.UPDATE_USERID :=        NVL ( RTRIM ( :NEW.UPDATE_USERID ), ' ' ) ;
  :NEW.ENTRY_USERID :=         NVL ( RTRIM ( :NEW.ENTRY_USERID ), ' ' ) ;
  END ;




/
ALTER TRIGGER "THE"."TB1$_GENERAL_INVOICE" ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "THE"."TB1$_INVC_NOTATION" 
   BEFORE INSERT OR UPDATE ON THE.INVC_NOTATION
   FOR EACH ROW
BEGIN
  :NEW.INVOICE_NUMBER :=     NVL ( RTRIM ( :NEW.INVOICE_NUMBER ), ' ' ) ;
  :NEW.CANCELLATION_IND :=   NVL ( RTRIM ( :NEW.CANCELLATION_IND ), ' ' ) ;
  :NEW.NOTATION_TYPE_CD :=   NVL ( RTRIM ( :NEW.NOTATION_TYPE_CD ), ' ' ) ;
  :NEW.ENTRY_USERID :=       NVL ( RTRIM ( :NEW.ENTRY_USERID ), ' ' ) ;
  :NEW.UPDATE_USERID :=      NVL ( RTRIM ( :NEW.UPDATE_USERID ), ' ' ) ;
  :NEW.NOTATION_TEXT :=      NVL ( RTRIM ( :NEW.NOTATION_TEXT ), ' ' ) ;
END ;




/
ALTER TRIGGER "THE"."TB1$_INVC_NOTATION" ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "THE"."TB1$_ACK_MASK" 
   BEFORE INSERT OR UPDATE ON THE.ACK_MASK
   FOR EACH ROW
BEGIN
   :NEW.ACK_MASK_ACODE :=     NVL ( RTRIM ( :NEW.ACK_MASK_ACODE ), ' ' ) ;
   :NEW.DESCRIPTION :=        NVL ( RTRIM ( :NEW.DESCRIPTION ), ' ' ) ;
   :NEW.DFLT_OCG_MNSTRY_ID := NVL ( RTRIM ( :NEW.DFLT_OCG_MNSTRY_ID ), ' ' ) ;
   :NEW.RESPONSE_CENTRE_CD := NVL ( RTRIM ( :NEW.RESPONSE_CENTRE_CD ), ' ' ) ;
   :NEW.RCC_VALIDATION_TBL := NVL ( RTRIM ( :NEW.RCC_VALIDATION_TBL ), ' ' ) ;
   :NEW.DEFAULT_ACCT_NUM :=   NVL ( RTRIM ( :NEW.DEFAULT_ACCT_NUM ), ' ' ) ;
   :NEW.DEFAULT_STOB :=       NVL ( RTRIM ( :NEW.DEFAULT_STOB ), ' ' ) ;
   :NEW.GL_PROJ_VLDTN_CD :=   NVL ( RTRIM ( :NEW.GL_PROJ_VLDTN_CD ), ' ' ) ;
   :NEW.GL_SPLR_VLDTN_CD :=   NVL ( RTRIM ( :NEW.GL_SPLR_VLDTN_CD ), ' ' ) ;
   :NEW.SUMMARIZE_IND :=      NVL ( RTRIM ( :NEW.SUMMARIZE_IND ), ' ' ) ;
   :NEW.UPDATE_USERID :=      NVL ( RTRIM ( :NEW.UPDATE_USERID ), ' ' ) ;
END ;





/
ALTER TRIGGER "THE"."TB1$_ACK_MASK" ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "THE"."TB1$_INVOICE_DTL_TXN" 
   BEFORE INSERT OR UPDATE ON THE.INVOICE_DTL_TXN
   FOR EACH ROW
BEGIN
  :NEW.INVOICE_NUMBER     := NVL(RTRIM(:NEW.INVOICE_NUMBER), ' ');
  :NEW.UNIT_OF_MEASURE_CD := NVL(RTRIM(:NEW.UNIT_OF_MEASURE_CD), ' ');
  :NEW.OCG_SUPPLIER_NMBR  := NVL(RTRIM(:NEW.OCG_SUPPLIER_NMBR), ' ');
  :NEW.ACK_MASK_ACODE     := NVL(RTRIM(:NEW.ACK_MASK_ACODE), ' ');
  :NEW.UPDATE_USERID      := NVL(RTRIM(:NEW.UPDATE_USERID), ' ');
  :NEW.ENTRY_USERID       := NVL(RTRIM(:NEW.ENTRY_USERID), ' ');
  :NEW.LINE_ITEM_DESCR    := NVL(RTRIM(:NEW.LINE_ITEM_DESCR), ' ');
END;




/
ALTER TRIGGER "THE"."TB1$_INVOICE_DTL_TXN" ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "THE"."TB1$_NOTATION_TXN" 
     BEFORE INSERT OR UPDATE ON THE.NOTATION_TXN
     FOR EACH ROW
BEGIN
   :NEW.INVOICE_NUMBER :=       NVL ( RTRIM ( :NEW.INVOICE_NUMBER ), ' ' ) ;
   :NEW.ENTRY_USERID :=         NVL ( RTRIM ( :NEW.ENTRY_USERID ), ' ' ) ;
   :NEW.UPDATE_USERID :=        NVL ( RTRIM ( :NEW.UPDATE_USERID ), ' ' ) ;
   :NEW.NOTATION_TEXT :=        NVL ( RTRIM ( :NEW.NOTATION_TEXT ), ' ' ) ;
 END ;




/
ALTER TRIGGER "THE"."TB1$_NOTATION_TXN" ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "THE"."TB1$_GEN_INVOICE_DTL" 
        BEFORE INSERT OR UPDATE ON THE.GEN_INVOICE_DTL
        FOR EACH ROW
BEGIN
  :NEW.INVOICE_NUMBER :=        NVL ( RTRIM ( :NEW.INVOICE_NUMBER ), ' ' ) ;
  :NEW.CANCELLATION_IND :=      NVL ( RTRIM ( :NEW.CANCELLATION_IND ), ' ' ) ;
  :NEW.REVENUE_CLASSN_CD :=     NVL ( RTRIM ( :NEW.REVENUE_CLASSN_CD ), ' ' ) ;
--  :NEW.RESPONSE_CENTRE_CD :=    NVL ( RTRIM ( :NEW.RESPONSE_CENTRE_CD ), ' ' ) ;
  :NEW.UNIT_OF_MEASURE_CD :=    NVL ( RTRIM ( :NEW.UNIT_OF_MEASURE_CD ), ' ' ) ;
  :NEW.OCG_SUPPLIER_NMBR :=     NVL ( RTRIM ( :NEW.OCG_SUPPLIER_NMBR ), ' ' ) ;
  :NEW.LINE_ITEM_DESCR :=       NVL ( RTRIM ( :NEW.LINE_ITEM_DESCR ), ' ' ) ;
  :NEW.UPDATE_USERID :=         NVL ( RTRIM ( SUBSTR(:NEW.UPDATE_USERID,0,8) ), ' ' ) ;
  :NEW.ENTRY_USERID :=          NVL ( RTRIM ( SUBSTR(:NEW.ENTRY_USERID,0,8) ), ' ' ) ;
 END ;




/
ALTER TRIGGER "THE"."TB1$_GEN_INVOICE_DTL" ENABLE;
